### ISSUE TITLE
OA2 to OA3 conversion incorrect if collectionFormat is missing

### ISSUE THREAD

**Issue by lmazuel** [Azure/perks#117]
Default in OA2: /users?id=3,4,5
Default in OA3: /users?id=3&id=4&id=5

So the converter should consider "no collectionFormat" as "form/false" (same behavior as "csv")
https://swagger.io/docs/specification/serialization/
https://swagger.io/docs/specification/2-0/describing-parameters/

**Comment by daviwil** [comment]
@lmazuel When you have a chance could you verify that the default `collectionFormat` of `csv` is getting propagated through correctly as `style: form`?  You might need to `autorest --reset` so that these changes get picked up when `@autorest/core` gets reinstalled.

**Comment by iscai-msft** [comment]
@daviwil can confirm with [this](https://github.com/Azure/autorest.testserver/pull/198) latest testserver test that I'm getting default `csv` behavior when `collectionFormat` is not specified. 

PSA: After talking offline with you, in order to get this change you need more than just `autorest --reset`, you also need to use version `3.0.6287` of autorest core

**Comment by daviwil** [comment]
Awesome thanks for verifying!
